### ISSUE TITLE
Options for Visibility and Customization 

### ISSUE THREAD

**Issue by TheHypnotist333** [lichess-org/mobile#1004]
One some boards such as "olive" it is difficult to see the green move indicator with my colorblindness. It would be useful to be able to change the color of the move indicator to increase visibility.
Similarly, the ability to change the color of the boards on the website also allows us to increase visibility. It would be nice to have this option in the app as well.

**Comment by EmmetSchuler** [comment]
Hue and brightness customization would be a nice addition.

1) Maybe we should add the option within the set of colored boards where you can adjust the hue and brightness of an individual board, similar to the web.

2) Or instead, to make it even simpler we could use a color wheel on a blank 'custom' board. I believe the current implementation of changing the hue and brightness takes the current board color and adjusts from there. But because that would need to be applicable to every board option, a color wheel on a blank 'custom' board (found on its own next to the other boards) could simplify that process.

**Comment by tom-anders** [comment]
Should be closed via https://github.com/lichess-org/mobile/pull/1251 I think

**Comment by TheHypnotist333** [comment]
Thank you! This solution is bugging me though. I cannot change the color of the move indicator as I requested without also changing the color of the board/arrows/annotations, and changing the color of the board doesn't also change the app. The result is in my attempt to change color for increased visibility I make the app look aesthetically unappealing. Would it be possible to allow us to independently change color board, move indicator, and app background independently? Having the app background set to "system colors" doesn't reflect my system colors. Us creative types will always appreciate the ability to control the aesthetics of the app in a simple way, right now it's obscure and I can't increase visibility without making the app look funny.
