### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [lichess-org/mobile#1074]

**Comment by veloce** [comment]
We know about that. Firebase allows us to provide a push notification service. For now the plan is not to get rid of firebase but to provide later a flavour of the app without it (and so without push notifications).

**Comment by Hgttgf** [comment]
There appear to be foss alternatives for notifications such as [uniqush](https://github.com/uniqush)

Users may assume that ["Lichess is safe, because it is free of ads and trackers... Ads and trackers violate our privacy, make websites much slower, and deliver dangerous malware. We say no to them."](https://lichess.org/ads) discarding firebase asap would make this ideal reality. Until you do, I'll exercise "...the right to refuse downloading source code that works against us."

Sorry if it's a difficult request. Would've helped ya if I knew programmimg.
