### ISSUE TITLE
Puzzle Themes Design

### ISSUE THREAD

**Issue by tedzards509** [lichess-org/mobile#229]
The Puzzle Themes selector is currently just a list of all puzzle themes sorted by topics:

<img src="https://github.com/lichess-org/mobile/assets/37296713/e4f0607b-f989-4f5a-b57e-b45715ca70ce" data-canonical-src="https://github.com/lichess-org/mobile/assets/37296713/e4f0607b-f989-4f5a-b57e-b45715ca70ce" width="400"/>

This feels very overwhelming and scrolling to a topic in the middle is annoying. Therefore the main idea of this redesign would be to move the topics themselves to an overseeable set of cards that direct to a submenu for each of the topics by themselves.

This idea can be either implemented by **(A)** just changing the `puzzle_themes_screen` or by **(B)** swapping the themes vs the "Puzzle Training" on the `puzzle_dashboard_screen` and adding the healthy mix as an emphasized button (like it it on the website, however this would add more taps to playing puzzles). I drew up designs for both ideas:

![PuzzleThemeDesign](https://github.com/lichess-org/mobile/assets/37296713/5601fff1-2879-425d-aa63-36d3719c5011)

I personally prefer idea **B** as in my perception people prefer the gamified puzzles over barebones "Healthy Mix" puzzles, so it being less present is outweighed by the themes being more accessible. Especially as it fits on a single page (see idea B1). I am however open to discussing different ideas.

**Comment by veloce** [comment]
Nice sketches! 

One thing first: landscape on mobile is not supported (only tablets).

I'm not 100% sure I understand correctly, but here are my thoughts:

**- Idea B** 
is not possible imo because we don't want to put on the save level Puzzle Storm, Puzzle Streak and puzzle themes; I'm not sure what people prefer, but in the website "Healthy mix" is the first choice, and it should be the same in the app; themes are more an advanced feature

**- Idea A** 
can be done if it's just a reorganisation of the theme screen; but I don't really get your drawings. Are you suggesting 2 alternatives? Screen on the left with the squares doesn't look possible. What do you put as a description here? We don't have any for now. It we want to add a description it should be synced with the website and involves a consequent work of translation. We already have descriptions at the lower level, we should keep it like that.

So only the screen on the right can be done, which is maybe an improvement.

**Comment by veloce** [comment]
Closing in favour of #310
