### ISSUE TITLE
Perf stats screen

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#23]
Create the performance screen for each time control and variant. Those screens are accessed from the corresponding "perf" card in the profile screen.

See on lichess.org: 
- https://lichess.org/@/Shant7777777/perf/bullet
- https://lichess.org/@/veloce/perf/blitz

Note the difference between the first and second: the second correspond to the logged in user profile, the working is different.

See lichess API reference to obtain the data: https://lichess.org/api#tag/Users/operation/apiUserPerf

**Comment by Dante-010** [comment]
Is it ok if I (try to) create everything but the graph?
I would also like to apologize in advance for any misinterpretations, mistakes, or troubles I may cause; this is my first time contributing to open source.

**Comment by Dante-010** [comment]
Don't know if it's necessary to post this, but here's how the UI is coming along:
 
![ui](https://user-images.githubusercontent.com/66489857/213090597-09a338a2-237f-4295-a319-f096696141fa.jpg)

I'm mostly done with business logic, and I should finish the UI by tomorrow. Then I'll add some tests to finish this off.

If there is anything you wish me to change, please tell me.

**Comment by veloce** [comment]
I'd probably display information differently, but that's too hard to describe here precisely what I want.

Your UI is clear but some informations are more important that other and here everything is display at the same level.
I'd try to use the `PlatformCard` widget for more important infos.

Here I don't see "Highest rating" and "Winning streak". Are they accessible on lichess API?

**Comment by Dante-010** [comment]
Ok, I'll try to implement PlatformCard and change some of the layout. As you can see, designing UI is not something I can do well, so I tried making it as simple as possible in order to make it easy to change in the future.

I have already implemented "Highest rating" and "Winning streak", I simply didn't show them in this screenshot. They both are accessible through the API, and can be found inside "stat" in the JSON response from this link: https://lichess.org/api#tag/Users/operation/apiUserPerf.

Thank you for your response! I'll be getting back in touch as soon as I can.

**Comment by Dante-010** [comment]
Here's the new UI layout (still a WIP):
![new_ui](https://user-images.githubusercontent.com/66489857/213631888-6caaf764-ff8f-4282-9c07-c0ad71364af3.jpg)

Don't worry if you see missing/wrong values, it's just that my development environment's database is not properly populated. I've already tested that these stats work. 

If you want to, once I'm done with it, I can send you screenshots for all the stats.

If you think this is OK, I'll go on to write some tests and, if everything is fine, make the pull request.
