### ISSUE TITLE
Notifications without GSF

### ISSUE THREAD

**Issue by FukS0cy** [lichess-org/mobile#257]
Since you are developing the app from scratch, I wanted to ask if it is possible to include notifications on Android without relying on Google Play services. With the old app, it was possible to develop the app without the Google Play services, but then you didn't get notifications at all. Maybe consider adding an alternative option to the app for users who want to get rid of Google but still want working notifications.
I often play with friends in casual mode and we make moves throughout the day when we have time, and right now they always have to send me a message in a messanger app when they challenge me to a game or have made their move, which is not very convenient. I see Lichess as a good alternative to e.g. chess.com because it is free and open source, the only point that is not free is the implementation of the notifications. Maybe we should consider releasing a version with GSF on Play Store and one without on F-Droid. Also, I would like to thank all the contributors who created such a good chess website/app.

**Comment by M00NJ** [comment]
I'd like to see this feature as well, it's very important from a privacy perspective.

**Comment by veloce** [comment]
I don't know an easy way to get push notification without google play services. Do you?

**Comment by M00NJ** [comment]
I'm very new to coding and I started of with learning Kotlin and Compose, so unfortunately I cannot contribute to projects written in Flutter / Dart yet. But I know that FluffyChat, which is also written in Flutter, has working push notifications without GSF.

**Comment by M00NJ** [comment]
But I also understand that there are more important features missing at the moment.

**Comment by veloce** [comment]
I'll have a look at fluffychat. Thanks for the tip.

**Comment by shuvashish76** [comment]
Have a look on
https://ntfy.sh/
https://unifiedpush.org/

**Comment by veloce** [comment]
Thank you for these suggestions of alternative options to Firebase. I have considered them but none of them was really entirely satisfying because of the added complexity they'd bring and the uncertain result in terms of reliability.

We have not enough resources I'm afraid to handle push notification differently, it is a quite complex topic. So we'll stick to Firebase for now as it is by far the simplest solution and is proven to work. 

For a completely FOSS version of the app, we can make a flavour of it without Firebase (and so without push notification). As it was done in the old app.
I'll create a separate issue for that.
