### ISSUE TITLE
Out of sync board status 

### ISSUE THREAD

**Issue by S1M0N38** [lichess-org/mobile#273]
![Screenshot_2023-08-11-08-42-13-114_org.lichess.mobileV2.jpg](https://github.com/lichess-org/mobile/assets/22257750/a10902cd-a11b-413e-99ab-beb6773b2674)

I was able to reach this position and my time runs out. So it should be a draw because my opponent does not have enough pieces to deliver a checkmate. 

But I lost.

I checked the games log and it seems that my final move wasn't able to reach servers. 

![Screenshot_2023-08-11-08-43-29-931_org.lichess.mobileV2.jpg](https://github.com/lichess-org/mobile/assets/22257750/b768e897-bdff-4a80-b413-39f958069242)

So black win is the correct result but I think that it's a bug to see a move on my board that was not delivered to the servers.

**Comment by veloce** [comment]
Normally the app with try to resend move automatically if it never reached the server but it can take a few seconds and you still might lose on time.
Now if the move never reach server and you lose on time the board should not stay ouf of sync. The fix made here should fix that, because it forces a resync if the server never replies after the move is made.

If you see again the problem when the next version of the app is released you can open another issue. Thanks.
