### ISSUE TITLE
Analysis move list and NAG icon GUI improvement

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#374]
I'm very glad to see how far we've come, now I'd like to make a suggestion related to the server analysis.

In my opinion it'd be better if the text of the move list and the NAG icons of server analysis should be consistent across all platforms of Lichess.

The move annotations on the Lichess website are color coded, making the key points of the game easier to notice. For example, the text itself of the move and the annotation is colored red if it was a blunder, orange if it was a mistake etc.

Another thing that should be consistent is the inaccuracy NAG icon, which is yellow currently. Both on the Lichess website and in the old mobile app, it was always and is cyan/light blue.

I know it was mentioned very early at the beginning of the development that it's not the goal to copy the website/old Lichobile, but these are features that were always the way they are now. I really don't want to unnecessarily complain...

So please consider coloring the text of the affected moves and making the inaccuracy NAG icon cyan. Let me know what you think and thanks a lot as always!

**Comment by veloce** [comment]
There is also the import PGN feature, where more move annotations (!!, !, etc.) are available. You need to find a coherent set of colors to represent all the annotations. In my opinion cyan color is not a good choice for inaccuracies. I'd rather have consistent colors across the app but I guess should make an exception just for lichess server analysis, otherwise people will complain.
