### ISSUE TITLE
Incorrect Game Time Displayed after Opponent Timeout

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#440]
### What is the problem?

Lichess mobile app v2 behavior is that when replaying the moves of a game it will sync the clock time of when that move was played.
When an opponent times out, however, the clock will sync to the time of his last played move. This can create confusion on how your opponent lost on time, as was in my case. The opponent's clock syncs to the time of his last played move, and not the time of the game result, which is to be expected.

### Steps to reproduce the bug

Challenge a player to a chess game
Let them run out of time

### What did you expect to happen?

After the game ends the time of the opponent's clock should be at zero seconds, like the behavior of the website and older mobile app.
![Screenshot_20240104-141914](https://github.com/lichess-org/mobile/assets/108140722/5e4b95fd-ab0f-416f-9de4-f2be5a088d1a)

### What happened instead?

The opponent's time switches to his last played move, and not the time of the game result.
![Screenshot_20240104-134036](https://github.com/lichess-org/mobile/assets/108140722/29aebb27-05f3-4ae5-afcd-2bd9be0820a4)

### Device Info

Pixel 6

### Operating System Version

Android 14

### Additional information

I understand this is probably low priority, but it deviates from the behavior of the website and v1 app, and can cause some confusion.

**Comment by veloce** [comment]
I understand why it's confusing: because on lichess website, on game page, we're displaying the last clock state, so when there is a timeout the clock is at 0.

Now if you look at the website game analysis screen, you'll see that tiny clocks are displayed and it matches the mobile V2 behaviour. It just shows time left for each player at each move, so it is normal that for a timeout we don't see 0, but the time left before it has reached 0.

Due to lack of space to display the clocks in the analysis screen I chose to display the "analysis" clocks for finished games in the game screen.

The confusion arises when a game is just finished and suddenly the clock goes from 0 to the last clock time at last move. 

Not sure how to deal with this, because when you review a game, the most useful information is the time left on the clock at each move.
