### ISSUE TITLE
Puzzle Streak: enable engine analysis after wrong move

### ISSUE THREAD

**Issue by stephanhuebsch** [lichess-org/mobile#595]
After revealing the solution to a (regular) puzzle, it is possible to analyze the board using the engine. 

It would be nice if this feature also existed after getting a puzzle wrong in puzzle streak. Right now, it's only possible to share the puzzle, open it in a browser and using the browser version of Lichess - or continue with a new streak.

**Comment by HaonRekcef** [comment]
What is your opinion, Veloce, should an evaluation bar appear, or should the user have the option to analyze the last puzzle of the puzzle streak?
Also, for normal puzzles, shouldn't there be the option to analyze them with the analysis board instead of just the evaluation?
I would try to implement this.

**Comment by veloce** [comment]
Yes we should be able to analyse the last puzzle in streak. 

And also with regular puzzles. I guess we should keep the bar here but also have a button to launch the analysis screen.

**Comment by HaonRekcef** [comment]
this can be closed due to #610
