### ISSUE TITLE
Can no longer play anonymous games

### ISSUE THREAD

**Issue by casbarof** [lichess-org/mobile#687]
### What is the problem?

As of 0.8.9, it’s no longer possible to play anonymous games. As the website still supports anonymous games, I assume this is a bug.

### Steps to reproduce the bug

Open the app. Cannot play a game without logging in.

### What did you expect to happen?

Can play anonymous games.

### What happened instead?

 Can’t play anonymous games.

### Device Info

iPad Pro M2

### Operating System Version

iPadOS 17.5

**Comment by veloce** [comment]
Can you explain why is it not possible anymore? Do you see an error or something?

**Comment by ijm8710** [comment]
I think they're not aware that you can click the plus icon in top right

**Comment by casbarof** [comment]
“Home” only has two links: “Sign in” and “About lichess”. The controls to start a game only appear once logged in.

**Comment by ijm8710** [comment]
Top right there is a plus sign

**Comment by casbarof** [comment]
@ijm8710 There is no plus sign on my screen.

**Comment by ijm8710** [comment]
> @ijm8710 There is no plus sign on my screen.

Would help to share picture of your home then

**Comment by casbarof** [comment]
@ijm8710 Are you aware that this repo is for the new beta app, and that we’re talking about 0.8.9 specifically?

**Comment by ijm8710** [comment]
> @ijm8710 Are you aware that this repo is for the new beta app, and that we’re talking about 0.8.9 specifically?

Yes I'm aware. But you keep not sharing the picture of the home screen. If Veloce needs to debug why the plus sign is not appearing I'm sure he can look into it but frankly I'm still slightly skeptical you don't have it

**Comment by casbarof** [comment]
Only you asked for it, and you don’t seem to be a maintainer. I don’t need a plus sign to start a game after signing in. Why would I need a plus sign when I’m not signed in? Doesn’t make sense.

**Comment by casbarof** [comment]
![IMG_0069](https://github.com/lichess-org/mobile/assets/169491148/f7a470f7-ea97-4185-bdcd-4a8c079684ae)

**Comment by ijm8710** [comment]
> Only you asked for a screenshot, and you don’t seem to be a maintainer. I don’t need a plus sign to start a game after signing in. Why would I need a plus sign when I’m not signed in? Doesn’t make sense.

Veloce asked if you had any error messages which you didn't provide any.
So first instinct was that maybe you didn't realize that where the new mechanism for the create game is.
And actually, you do need the plus sign to start a game now when logged in.
Even more relevant, when logged out, there SHOULD be a plus sign to start a game then as well, so that is why I asked if you had it. 
I fully state that you are correct and it does indeed look bugged and  my skepticism was not applicable here, but almost any way to debug this begins with confirming that the plus sign was indeed missing.

@Veloce  probably worth a look maybe something to do with iPads or something?

**Comment by casbarof** [comment]
> And actually, you do need the plus sign to start a game now when logged in.

Absolutely not. Once I’m logged in, there’s a huge “Play” button.

**Comment by ijm8710** [comment]
> > And actually, you do need the plus sign to start a game now when logged in.
> 
> 
> 
> Absolutely not. Once I’m logged in, there’s a huge “Play” button, and still no plus sign.

Unless Veloce designed a diff design for tablets which u doubt, what you're seeing i don't think is expected

This is what it should look like for when you are logged in. Note the plus icon in the top right. That is the only mechanism  to start a new game regardless of if you're logged in or not
![image](https://github.com/lichess-org/mobile/assets/25938701/ce5e3aae-a0ae-4639-9785-917117997bfb)

IMO there may be value to share what your homefeed looks like when logged in to because as far as I understand this huge play button is NOT normal behavior but it's yo to you if you want to share that too.

**Comment by veloce** [comment]
Yes there is a problem on tablet, will fix it. Thanks for the feedback.

**Comment by iamnabink** [comment]
Hi @veloce,

I just reproduced this issue on the iPad Pro 6th generation. It looks like the plus button is not displaying on the iPad mainly because of this check:

```
if (isHandset)
    ...[
        const SizedBox(width: 6.0),
        AppBarIconButton()
    ]
```
The visibility is controlled by `isHandset()`. I want to clarify whether this is an intended handset check. If we remove that condition, the button will be visible on any device, which should resolve the issue.

I'll go ahead and make a PR. If that's fine with you, please merge it.
