### ISSUE TITLE
Custom time slider uses seconds format in the minutes field

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#824]
### What is the problem?

The custom time slider in both the clock and create a game screen displays the amount of seconds instead of minutes in the minutes section. This looks like 120 for two minutes, and really high numbers for larger time controls.

### Steps to reproduce the bug

Go to clock
Pick a custom time control
In the minutes section, slide your finger across the slider

### What did you expect to happen?

You should see individual minutes

### What happened instead?

You see the time in seconds format instead. This is confusing and unintuitive.

### Device Info

N/a

### Operating System Version

Android 14

### Additional information

Screenshot
![Screenshot_20240702-181344](https://github.com/lichess-org/mobile/assets/108140722/c0006be2-24e4-483a-8089-e0135dc6d73b)

**Comment by veloce** [comment]
Good catch, thanks for the report.

**Comment by ijm8710** [comment]
@veloce I still strongly believe on iOS the typical iOS time picker would better fit for both the clock tool and custom game creation ![image](https://github.com/lichess-org/mobile/assets/25938701/2bc12e54-649b-4807-b6bd-c3bdee99aec2)

**Comment by BAW2501** [comment]
I have identified the issue with the nonlinear slider lacking a label builder. To resolve this, we can use the `_clockTimeLabel` function, which has been used previously. Here is the suggested change:

```diff dart
child: NonLinearSlider(
value: custom.time,
values: kAvailableTimesInSeconds,
+ labelBuilder: _clockTimeLabel,
...
...
+ String _clockTimeLabel(num seconds) {
+  switch (seconds) {
+    case 0:
+      return '0';
+    case 45:
+      return '¾';
+    case 30:
+      return '½';
+    case 15:
+      return '¼';
+    default:
+      return (seconds / 60).toString().replaceAll('.0', '');
+  }
+}
```

However, this will be the third instance of this code snippet in the codebase. To avoid redundancy, we should refactor this into a single function within a utilities package ( I'm unaware where, please suggest where). This function can then be imported and used in the following files:

- `time_control_modal.dart`
- `create_custom_game_screen.dart`
- `challenge_screen.dart`

Additionally, it can be utilized in `time_increment.dart`.

@veloce, could you provide some input on this? If you decide on refactoring, please create a new task and I'll get working on it. Otherwise, I'll push the changes as mentioned.

**Comment by veloce** [comment]
Thanks for the input @BAW2501 , I made the refactoring .
